### ISSUE TITLE
Add some details in Trello cards

### ISSUE THREAD

**Issue by SergArtuh** [SkillerRaptor/hyper_engine#1]
Hi!

The project looks interesting to me.

I assume it would be a good idea to add subtasks or at least a minimum description in your Trello cards.

**Comment by SkillerRaptor** [comment]
Hello,

Thanks for the feedback. I will definetly do that in the next days and add some more description to the Trello Cards. If something is still wrong with the new cards, then feel free to add some details what you would change then. If there's nothing to say anymore, you can close this issue now.

**Comment by SkillerRaptor** [comment]
Hello,

I changed now the trello board structure and added some details to the cards. I hope the new design is now better. If there's any improvements or idea, please let me know.
