### ISSUE TITLE
Add uniform buffer object

### ISSUE THREAD

**Issue by SergArtuh** [SkillerRaptor/hyper_engine#2]
You probably should add support [uniform buffer](https://www.khronos.org/opengl/wiki/Uniform_Buffer_Object) instead of setting up plenty of uniforms for every time you want to use your shader.

```c++
m_ShaderManager->SetMatrix4({ 1 }, "u_ProjectionMatrix", projectionMatrix);
m_ShaderManager->SetMatrix4({ 1 }, "u_ViewMatrix", viewMatrix);
```

There is one more advantage, you could easily share UBO for set up the camera stuff, lights, or any other uniforms you want to share between shaders.

**Comment by SkillerRaptor** [comment]
Hello,

Thank you for the feedback. I will definitely put it to my to-do list. In the moment all uniform are hardcoded into a specific shader. I will add the uniform buffer object, when I have a proper assets manager to handle the shaders better. It is good idea to share the uniforms between the shaders for less driver overhead. Also I think it is a good idea to make use of it in the material system.

I will keep track of this and add some updates to the UBO implementation. This issue will be closed, when the uniform buffer object is implemented.

**Comment by SkillerRaptor** [comment]
This issue will be closed, because of an outdated version of the engine.
